import * as XLSX from "xlsx";

export const downloadQuizSampleXlsx = () => {
  const sampleData = [
    {
      Topic: "Java Basics",
      Question: "What is JVM?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "Java Virtual Machine",
      "Option B": "Java Variable Machine",
      "Option C": "Java Vendor Machine",
      "Option D": "Java Version Manager",
      "Correct Answers": "A",
      Difficulty: "EASY",
      Explanation: "JVM executes Java bytecode.",
    },
    {
      Topic: "Java Basics",
      Question: "Which keyword is used for inheritance in Java?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "extends",
      "Option B": "implements",
      "Option C": "inherit",
      "Option D": "super",
      "Correct Answers": "A",
      Difficulty: "EASY",
      Explanation: "extends is used for inheritance.",
    },
    {
      Topic: "Java Basics",
      Question: "Which of the following are primitive data types in Java?",
      "Question Type": "MULTIPLE_CHOICE",
      "Option A": "int",
      "Option B": "String",
      "Option C": "boolean",
      "Option D": "float",
      "Correct Answers": "A,C,D",
      Difficulty: "EASY",
      Explanation: "String is not primitive.",
    },
    {
      Topic: "OOP",
      Question: "Which principle hides implementation details?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "Encapsulation",
      "Option B": "Polymorphism",
      "Option C": "Inheritance",
      "Option D": "Abstraction",
      "Correct Answers": "A",
      Difficulty: "EASY",
      Explanation: "Encapsulation hides implementation details.",
    },
    {
      Topic: "OOP",
      Question: "Which keyword refers to the current object in Java?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "this",
      "Option B": "super",
      "Option C": "self",
      "Option D": "current",
      "Correct Answers": "A",
      Difficulty: "EASY",
      Explanation: "this references the current object.",
    },
    {
      Topic: "Collections",
      Question: "Which interface does ArrayList implement?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "List",
      "Option B": "Set",
      "Option C": "Queue",
      "Option D": "Map",
      "Correct Answers": "A",
      Difficulty: "MEDIUM",
      Explanation: "ArrayList implements List.",
    },
    {
      Topic: "Collections",
      Question: "Which collection stores unique values in Java?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "Set",
      "Option B": "List",
      "Option C": "Queue",
      "Option D": "ArrayList",
      "Correct Answers": "A",
      Difficulty: "MEDIUM",
      Explanation: "Set stores unique values.",
    },
    {
      Topic: "Collections",
      Question: "Which methods are available in List?",
      "Question Type": "MULTIPLE_CHOICE",
      "Option A": "add()",
      "Option B": "get()",
      "Option C": "push()",
      "Option D": "remove()",
      "Correct Answers": "A,B,D",
      Difficulty: "MEDIUM",
      Explanation: "push() belongs to Stack.",
    },
    {
      Topic: "Exception",
      Question: "Which block always executes?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "finally",
      "Option B": "catch",
      "Option C": "throw",
      "Option D": "try",
      "Correct Answers": "A",
      Difficulty: "MEDIUM",
      Explanation: "finally executes regardless of exceptions.",
    },
    {
      Topic: "Exception",
      Question: "Which exception is unchecked?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "NullPointerException",
      "Option B": "IOException",
      "Option C": "SQLException",
      "Option D": "FileNotFoundException",
      "Correct Answers": "A",
      Difficulty: "MEDIUM",
      Explanation: "Runtime exceptions are unchecked.",
    },
    {
      Topic: "Multithreading",
      Question: "Which method starts a thread?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "start()",
      "Option B": "run()",
      "Option C": "execute()",
      "Option D": "begin()",
      "Correct Answers": "A",
      Difficulty: "HARD",
      Explanation: "start() creates a new thread.",
    },
    {
      Topic: "Multithreading",
      Question: "Which interface represents executable tasks?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "Runnable",
      "Option B": "Comparable",
      "Option C": "Serializable",
      "Option D": "Cloneable",
      "Correct Answers": "A",
      Difficulty: "HARD",
      Explanation: "Runnable represents executable tasks.",
    },
    {
      Topic: "Streams",
      Question: "Which package introduced Streams in Java 8?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "java.util.stream",
      "Option B": "java.io",
      "Option C": "java.sql",
      "Option D": "java.net",
      "Correct Answers": "A",
      Difficulty: "HARD",
      Explanation: "Streams were introduced in Java 8.",
    },
    {
      Topic: "Streams",
      Question: "Which operation is terminal?",
      "Question Type": "SINGLE_CHOICE",
      "Option A": "collect()",
      "Option B": "map()",
      "Option C": "filter()",
      "Option D": "peek()",
      "Correct Answers": "A",
      Difficulty: "HARD",
      Explanation: "collect() is a terminal operation.",
    },
    {
      Topic: "Streams",
      Question: "Which operations are non-terminal?",
      "Question Type": "MULTIPLE_CHOICE",
      "Option A": "map()",
      "Option B": "filter()",
      "Option C": "collect()",
      "Option D": "sorted()",
      "Correct Answers": "A,B,D",
      Difficulty: "HARD",
      Explanation: "collect() is terminal while map/filter/sorted are non-terminal.",
    },
  ];

  const worksheet = XLSX.utils.json_to_sheet(sampleData);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Quiz Questions");
  XLSX.writeFile(workbook, "quiz-questions-template.xlsx");
};
